spring:
  application:
    name: eureka-server
  security:
    user:
      name: wht
      password: 123456


server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://wht:123456@localhost:8080/eureka/
  server:
    renewal-percent-threshold: 0.49